---
apiVersion: v1
kind: Service
metadata:
  name: myakacrregistry
  labels:
    app: myakacrregistry
spec:
  type: NodePort
  selector:
    app: myakacrregistry
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myakacrregistry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myakacrregistry
    spec:
      containers:
      - name: myakacrregistry
        image: myakacrregistry/my-java-app:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
